# https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#configuring-the-template-chooser
blank_issues_enabled: true
contact_links:
  - name: Questions and Discussions
    url: https://github.com/moby/buildkit/discussions/new
    about: Use Github Discussions to ask questions and/or open discussion topics.
  - name: Documentation
    url: https://github.com/moby/buildkit/tree/master/docs
    about: Read the documentation.
  - name: Join the Docker Community on Slack
    url: http://dockr.ly/comm-slack
    about: Join the Docker Community on Slack and head to the buildkit channel.
