# This workflow is for builds on Windows. We cannot use the existing
# Travis-CI workflow as that depends on already having functioning
# BuildKit to run the v1.1-experimental Dockerfile that builds BuildKit.
name: Windows

on: [push, pull_request]

jobs:
  build:
    name: Build BuildKit
    runs-on: windows-2019
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - name: Checkout
        uses: actions/checkout@v2
        # Is this needed? Didn't Go Modules fix this?
        with:
          path: src/github.com/moby/buildkit
      - name: Compile
        run: go install -mod=vendor ./cmd/...
        working-directory: src/github.com/moby/buildkit

  unit_tests:
    name: Unit Tests
    runs-on: windows-2019
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.13
      - name: Checkout
        uses: actions/checkout@v2
        # Is this needed? Didn't Go Modules fix this?
        with:
          path: src/github.com/moby/buildkit
      - name: Unit test
        env:
          SKIP_INTEGRATION_TESTS: 1
        run: go test -mod=vendor -v ./frontend/dockerfile/... ./session/... ./util/...
        working-directory: src/github.com/moby/buildkit
